#!/usr/bin/env bash
# Configures Nginx to add a custom HTTP header X-Served-By on web servers
apt-get update -y
apt-get install -y nginx

# Remove existing X-Served-By headers and add a single correct header
sed -i '/add_header X-Served-By/d' /etc/nginx/sites-available/default
sed -i '/server_name _;/a \        add_header X-Served-By $hostname;' /etc/nginx/sites-available/default

# Sync changes to sites-enabled
cp /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Test and restart Nginx
nginx -t
systemctl restart nginx
