#!/usr/bin/env bash
# This script displays the content of the current directory in list format
for file in *; do
    # Ignore hidden files
    if [[ $file != .* ]]; then
        # Check if file contains a dash, then cut; otherwise, print the filename
        if [[ $file == *-* ]]; then
            echo "$file" | cut -d'-' -f2-
        else
            echo "$file"
        fi
    fi
done
