#!/usr/bin/env bash
# Configures an Ubuntu server with custom IP for localhost and facebook.com

# Make a copy of the original hosts file
cp /etc/hosts ~/hosts.new

# Replace localhost IP with 127.0.0.2
sed -i 's/127.0.0.1\slocalhost/127.0.0.2 localhost/g' ~/hosts.new

# Add facebook.com entry
echo "8.8.8.8 facebook.com" >> ~/hosts.new

# Copy the modified file back to /etc/hosts
cp -f ~/hosts.new /etc/hosts
